const fs = require('fs');
const path = require('path');

const themes = {
  alimentos: { accent: '#F59E0B', accentGlow: 'rgba(245, 158, 11, 0.4)', bgStart: '#140c01', bgEnd: '#291802', glowColor: 'amber' },
  packaging: { accent: '#FFD700', accentGlow: 'rgba(255, 215, 0, 0.4)', bgStart: '#121001', bgEnd: '#262102', glowColor: 'yellow' },
  conversion: { accent: '#06B6D4', accentGlow: 'rgba(6, 182, 212, 0.4)', bgStart: '#011012', bgEnd: '#032329', glowColor: 'cyan' },
  reciclaje: { accent: '#10B981', accentGlow: 'rgba(16, 185, 129, 0.4)', bgStart: '#01120c', bgEnd: '#022419', glowColor: 'emerald' },
  medica: { accent: '#EF4444', accentGlow: 'rgba(239, 68, 68, 0.4)', bgStart: '#170404', bgEnd: '#2e0808', glowColor: 'red' },
  automatizacion: { accent: '#8B5CF6', accentGlow: 'rgba(139, 92, 246, 0.4)', bgStart: '#0e0917', bgEnd: '#1c122e', glowColor: 'violet' }
};

const machinesList = [
  { ind: "alimentos", code: "mix", name: "Sistemas de Mezclado", desc: "Mezcla industrial para sólidos y formulaciones." },
  { ind: "alimentos", code: "cok", name: "Sistemas de Cocción", desc: "Procesamiento térmico continuo." },
  { ind: "alimentos", code: "bld", name: "Sistemas de Homogeneización", desc: "Mezcla uniforme y control de calidad." },
  { ind: "alimentos", code: "fws", name: "Lavado Alimenticio", desc: "Lavado y sanitización." },
  { ind: "alimentos", code: "dry", name: "Secado Industrial", desc: "Remoción controlada de humedad." },
  { ind: "alimentos", code: "chx", "name": "Procesamiento de Chocolate", desc: "Líneas completas para chocolate." },
  { ind: "alimentos", code: "snk", name: "Producción de Snacks", desc: "Extrusión y formado." },
  { ind: "alimentos", code: "bar", name: "Producción de Barras", desc: "Producción continua." },
  
  { ind: "packaging", code: "csl", name: "Encajonado", desc: "Agrupado automático." },
  { ind: "packaging", code: "pal", name: "Paletizado", desc: "Paletizado robotizado." },

  { ind: "conversion", code: "exf", name: "Extrusión de Película", desc: "Producción monocapa." },
  { ind: "conversion", code: "cbl", name: "Coextrusión Soplada", desc: "Película multicapa." },
  { ind: "conversion", code: "ccs", name: "Coextrusión Cast", desc: "Película plana multicapa." },
  { ind: "conversion", code: "ebm", name: "Extrusión Soplado", desc: "Fabricación de envases." },
  { ind: "conversion", code: "sbm", name: "Soplado Estirado", desc: "Producción PET." },
  { ind: "conversion", code: "ibm", name: "Inyección Soplado", desc: "Piezas técnicas." },
  { ind: "conversion", code: "flx", name: "Impresión Flexográfica", desc: "Impresión industrial." },
  { ind: "conversion", code: "grv", name: "Rotograbado", desc: "Alta calidad gráfica." },
  { ind: "conversion", code: "dig", name: "Impresión Digital", desc: "Producción flexible." },
  { ind: "conversion", code: "lam", name: "Laminación", desc: "Solvente y solventless." },
  { ind: "conversion", code: "slt", name: "Corte y Rebobinado", desc: "Conversión final." },
  { ind: "conversion", code: "thf", name: "Termoformado", desc: "Conformado térmico." },
  
  { ind: "reciclaje", code: "shd", name: "Trituración Industrial", desc: "Reducción de tamaño." },
  { ind: "reciclaje", code: "grn", name: "Granulación", desc: "Molienda." },
  { ind: "reciclaje", code: "pws", name: "Lavado de Plástico", desc: "Lavado de polímeros." },
  { ind: "reciclaje", code: "flt", "name": "Flotación", desc: "Separación por densidad." },
  { ind: "reciclaje", code: "fri", "name": "Lavado por Fricción", desc: "Limpieza intensiva." },
  { ind: "reciclaje", code: "spr", "name": "Separación Industrial", desc: "Clasificación de materiales." },
  { ind: "reciclaje", code: "opt", "name": "Clasificación Óptica", desc: "Separación automatizada." },
  { ind: "reciclaje", code: "plt", "name": "Peletizado", desc: "Recuperación de resina." },
  { ind: "reciclaje", code: "bal", "name": "Compactación", "desc": "Prensado de materiales." },
  
  { ind: "medica", code: "med", "name": "Conversión Sanitaria", desc: "Equipos para productos médicos." },
  { ind: "medica", code: "msk", "name": "Producción de Cubrebocas", desc: "Líneas de mascarillas." },
  
  { ind: "automatizacion", code: "rob", name: "Sistemas Robotizados", desc: "Robótica industrial." },
  { ind: "automatizacion", code: "vis", name: "Sistemas de Visión", desc: "Inspección automatizada." },
  { ind: "automatizacion", code: "dgt", "name": "Gemelo Digital", desc: "Simulación y monitoreo." }
];

let generatedCode = `// Autogenerated machinery data map
export const machineryDataMap = {
`;

machinesList.forEach((m, idx) => {
  const t = themes[m.ind];
  generatedCode += `  ${m.code}: {
    industry: '${m.ind}',
    machineCode: '${m.code}',
    pageNumber: '${String(idx + 10).padStart(2, '0')}',
    theme: {
      accent: '${t.accent}',
      accentGlow: '${t.accentGlow}',
      bgStart: '${t.bgStart}',
      bgEnd: '${t.bgEnd}',
      glowColor: '${t.glowColor}'
    },
    heroTitle: '${m.name.toUpperCase()}',
    heroSubtitle: '${m.desc}',
    heroDesc: 'Descripción detallada para ${m.name}. El sistema está diseñado para cumplir con los estándares industriales más exigentes. Puedes editar este contenido desde el CMS para especificar el funcionamiento exacto y los beneficios de esta línea.',
    heroMedia: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
    kpis: [
      { value: '100%', unit: 'EFICIENCIA', label: 'Rendimiento', desc: 'Producción continua' },
      { value: '24/7', unit: 'OPERACIÓN', label: 'Disponibilidad', desc: 'Sistemas redundantes' },
      { value: 'Auto', unit: 'CONTROL', label: 'Precisión', desc: 'Control avanzado por PLC' },
      { value: 'Premium', unit: 'CALIDAD', label: 'Estándar', desc: 'Materiales duraderos' }
    ],
    stations: [
      { id: 1, title: 'Alimentación', desc: 'Ingreso del material al sistema automatizado.', iconName: 'Inbox' },
      { id: 2, title: 'Procesamiento', desc: 'Transformación del producto bajo estrictos controles.', iconName: 'Layers' },
      { id: 3, title: 'Control de Calidad', desc: 'Verificación en línea del producto final.', iconName: 'Eye' },
      { id: 4, title: 'Descarga', desc: 'Salida del material terminado y empacado.', iconName: 'LogOut' }
    ],
    applications: [
      { name: 'Sector Primario', icon: '🏭', desc: 'Aplicación en las industrias de mayor demanda' },
      { name: 'Aplicación Especial', icon: '⚙️', desc: 'Procesos personalizados para este equipo' }
    ],
    advantages: [
      { title: 'ALTA CONFIABILIDAD', desc: 'Equipos diseñados para funcionar sin interrupciones con mínimo mantenimiento.', highlight: 'Durabilidad' },
      { title: 'INTEGRACIÓN 4.0', desc: 'Monitoreo remoto y conexión con sistemas de gestión de planta.', highlight: 'Tecnología' }
    ],
    specs: [
      { param: 'Modelo Base', value: 'Serie SMQ-${m.code.toUpperCase()}' },
      { param: 'Capacidad', value: 'Configurable según requerimientos' },
      { param: 'Controlador', value: 'PLC de última generación con pantalla HMI' }
    ],
    configurations: [
      { name: 'Automatización Completa', desc: 'Módulos adicionales para operación desatendida.' },
      { name: 'Sensores Avanzados', desc: 'Sistemas de inspección óptica y láser.' }
    ]
  },
`;
});

generatedCode += `};
`;

fs.writeFileSync(path.join(__dirname, 'apps/web/src/data/machineryCatalog.js'), generatedCode);
console.log('Catalog generated!');
